answer_paths:
  cases/eval_0-0-0.yaml:
  - eval_0-0-0_0.txt
  - eval_0-0-0_1.txt
  - eval_0-0-0_2.txt
  cases/eval_0-0-1.yaml:
  - eval_0-0-1_0.txt
  - eval_0-0-1_1.txt
  - eval_0-0-1_2.txt
  cases/eval_0-0-10.yaml:
  - eval_0-0-10_0.txt
  - eval_0-0-10_1.txt
  - eval_0-0-10_2.txt
  cases/eval_0-0-12.yaml:
  - eval_0-0-12_0.txt
  - eval_0-0-12_1.txt
  - eval_0-0-12_2.txt
  cases/eval_0-0-13.yaml:
  - eval_0-0-13_0.txt
  - eval_0-0-13_1.txt
  - eval_0-0-13_2.txt
  cases/eval_0-0-14.yaml:
  - eval_0-0-14_0.txt
  - eval_0-0-14_1.txt
  - eval_0-0-14_2.txt
  cases/eval_0-0-15.yaml:
  - eval_0-0-15_0.txt
  - eval_0-0-15_1.txt
  - eval_0-0-15_2.txt
  cases/eval_0-0-17.yaml:
  - eval_0-0-17_0.txt
  - eval_0-0-17_1.txt
  - eval_0-0-17_2.txt
  cases/eval_0-0-19.yaml:
  - eval_0-0-19_0.txt
  - eval_0-0-19_1.txt
  - eval_0-0-19_2.txt
  cases/eval_0-0-20.yaml:
  - eval_0-0-20_0.txt
  - eval_0-0-20_1.txt
  - eval_0-0-20_2.txt
  cases/eval_0-0-21.yaml:
  - eval_0-0-21_0.txt
  - eval_0-0-21_1.txt
  - eval_0-0-21_2.txt
  cases/eval_0-0-22.yaml:
  - eval_0-0-22_0.txt
  - eval_0-0-22_1.txt
  - eval_0-0-22_2.txt
  cases/eval_0-0-24.yaml:
  - eval_0-0-24_0.txt
  - eval_0-0-24_1.txt
  - eval_0-0-24_2.txt
  cases/eval_0-0-26.yaml:
  - eval_0-0-26_0.txt
  - eval_0-0-26_1.txt
  - eval_0-0-26_2.txt
  cases/eval_0-0-27.yaml:
  - eval_0-0-27_0.txt
  - eval_0-0-27_1.txt
  - eval_0-0-27_2.txt
  cases/eval_0-0-29.yaml:
  - eval_0-0-29_0.txt
  - eval_0-0-29_1.txt
  - eval_0-0-29_2.txt
  cases/eval_0-0-30.yaml:
  - eval_0-0-30_0.txt
  - eval_0-0-30_1.txt
  - eval_0-0-30_2.txt
  cases/eval_0-0-35.yaml:
  - eval_0-0-35_0.txt
  - eval_0-0-35_1.txt
  - eval_0-0-35_2.txt
  cases/eval_0-0-36.yaml:
  - eval_0-0-36_0.txt
  - eval_0-0-36_1.txt
  - eval_0-0-36_2.txt
  cases/eval_0-0-37.yaml:
  - eval_0-0-37_0.txt
  - eval_0-0-37_1.txt
  - eval_0-0-37_2.txt
  cases/eval_0-0-38.yaml:
  - eval_0-0-38_0.txt
  - eval_0-0-38_1.txt
  - eval_0-0-38_2.txt
  cases/eval_0-0-39.yaml:
  - eval_0-0-39_0.txt
  - eval_0-0-39_1.txt
  - eval_0-0-39_2.txt
  cases/eval_0-0-4.yaml:
  - eval_0-0-4_0.txt
  - eval_0-0-4_1.txt
  - eval_0-0-4_2.txt
  cases/eval_0-0-40.yaml:
  - eval_0-0-40_0.txt
  - eval_0-0-40_1.txt
  - eval_0-0-40_2.txt
  cases/eval_0-0-41.yaml:
  - eval_0-0-41_0.txt
  - eval_0-0-41_1.txt
  - eval_0-0-41_2.txt
  cases/eval_0-0-42.yaml:
  - eval_0-0-42_0.txt
  - eval_0-0-42_1.txt
  - eval_0-0-42_2.txt
  cases/eval_0-0-44.yaml:
  - eval_0-0-44_0.txt
  - eval_0-0-44_1.txt
  - eval_0-0-44_2.txt
  cases/eval_0-0-46.yaml:
  - eval_0-0-46_0.txt
  - eval_0-0-46_1.txt
  - eval_0-0-46_2.txt
  cases/eval_0-0-47.yaml:
  - eval_0-0-47_0.txt
  - eval_0-0-47_1.txt
  - eval_0-0-47_2.txt
  cases/eval_0-0-48.yaml:
  - eval_0-0-48_0.txt
  - eval_0-0-48_1.txt
  - eval_0-0-48_2.txt
  cases/eval_0-0-5.yaml:
  - eval_0-0-5_0.txt
  - eval_0-0-5_1.txt
  - eval_0-0-5_2.txt
  cases/eval_0-0-52.yaml:
  - eval_0-0-52_0.txt
  - eval_0-0-52_1.txt
  - eval_0-0-52_2.txt
  cases/eval_0-0-53.yaml:
  - eval_0-0-53_0.txt
  - eval_0-0-53_1.txt
  - eval_0-0-53_2.txt
  cases/eval_0-0-54.yaml:
  - eval_0-0-54_0.txt
  - eval_0-0-54_1.txt
  - eval_0-0-54_2.txt
  cases/eval_0-0-56.yaml:
  - eval_0-0-56_0.txt
  - eval_0-0-56_1.txt
  - eval_0-0-56_2.txt
  cases/eval_0-0-58.yaml:
  - eval_0-0-58_0.txt
  - eval_0-0-58_1.txt
  - eval_0-0-58_2.txt
  cases/eval_0-0-59.yaml:
  - eval_0-0-59_0.txt
  - eval_0-0-59_1.txt
  - eval_0-0-59_2.txt
  cases/eval_0-0-60.yaml:
  - eval_0-0-60_0.txt
  - eval_0-0-60_1.txt
  - eval_0-0-60_2.txt
  cases/eval_0-0-61.yaml:
  - eval_0-0-61_0.txt
  - eval_0-0-61_1.txt
  - eval_0-0-61_2.txt
  cases/eval_0-0-62.yaml:
  - eval_0-0-62_0.txt
  - eval_0-0-62_1.txt
  - eval_0-0-62_2.txt
  cases/eval_0-0-8.yaml:
  - eval_0-0-8_0.txt
  - eval_0-0-8_1.txt
  - eval_0-0-8_2.txt
  cases/eval_0-0-9.yaml:
  - eval_0-0-9_0.txt
  - eval_0-0-9_1.txt
  - eval_0-0-9_2.txt
  cases/eval_0-1-134.yaml:
  - eval_0-1-134_0.txt
  - eval_0-1-134_1.txt
  - eval_0-1-134_2.txt
  cases/eval_0-1-135.yaml:
  - eval_0-1-135_0.txt
  - eval_0-1-135_1.txt
  - eval_0-1-135_2.txt
  cases/eval_0-1-137.yaml:
  - eval_0-1-137_0.txt
  - eval_0-1-137_1.txt
  - eval_0-1-137_2.txt
  cases/eval_0-1-138.yaml:
  - eval_0-1-138_0.txt
  - eval_0-1-138_1.txt
  - eval_0-1-138_2.txt
  cases/eval_0-1-140.yaml:
  - eval_0-1-140_0.txt
  - eval_0-1-140_1.txt
  - eval_0-1-140_2.txt
  cases/eval_0-1-143.yaml:
  - eval_0-1-143_0.txt
  - eval_0-1-143_1.txt
  - eval_0-1-143_2.txt
  cases/eval_0-1-144.yaml:
  - eval_0-1-144_0.txt
  - eval_0-1-144_1.txt
  - eval_0-1-144_2.txt
  cases/eval_0-1-145.yaml:
  - eval_0-1-145_0.txt
  - eval_0-1-145_1.txt
  - eval_0-1-145_2.txt
  cases/eval_0-1-148.yaml:
  - eval_0-1-148_0.txt
  - eval_0-1-148_1.txt
  - eval_0-1-148_2.txt
  cases/eval_0-1-149.yaml:
  - eval_0-1-149_0.txt
  - eval_0-1-149_1.txt
  - eval_0-1-149_2.txt
  cases/eval_0-2-152.yaml:
  - eval_0-2-152_0.txt
  - eval_0-2-152_1.txt
  - eval_0-2-152_2.txt
  cases/eval_0-2-153.yaml:
  - eval_0-2-153_0.txt
  - eval_0-2-153_1.txt
  - eval_0-2-153_2.txt
  cases/eval_0-2-154.yaml:
  - eval_0-2-154_0.txt
  - eval_0-2-154_1.txt
  - eval_0-2-154_2.txt
  cases/eval_0-2-156.yaml:
  - eval_0-2-156_0.txt
  - eval_0-2-156_1.txt
  - eval_0-2-156_2.txt
  cases/eval_0-2-160.yaml:
  - eval_0-2-160_0.txt
  - eval_0-2-160_1.txt
  - eval_0-2-160_2.txt
  cases/eval_0-2-162.yaml:
  - eval_0-2-162_0.txt
  - eval_0-2-162_1.txt
  - eval_0-2-162_2.txt
  cases/eval_0-2-163.yaml:
  - eval_0-2-163_0.txt
  - eval_0-2-163_1.txt
  - eval_0-2-163_2.txt
  cases/eval_0-2-164.yaml:
  - eval_0-2-164_0.txt
  - eval_0-2-164_1.txt
  - eval_0-2-164_2.txt
  cases/eval_0-2-166.yaml:
  - eval_0-2-166_0.txt
  - eval_0-2-166_1.txt
  - eval_0-2-166_2.txt
  cases/eval_0-2-168.yaml:
  - eval_0-2-168_0.txt
  - eval_0-2-168_1.txt
  - eval_0-2-168_2.txt
max_tokens: null
model_name: gpt-4
qa_system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format. You are chatting with programmers, so please
  answer as briefly as possible.
sample_n: 3
system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format.
temp: 0.2
top_p: 0.9
