answer_paths:
  cases/eval_1443.yaml:
  - 6_0.txt
  - 6_1.txt
  - 6_2.txt
  cases/eval_1493.yaml:
  - 7_0.txt
  - 7_1.txt
  - 7_2.txt
  cases/eval_1799.yaml:
  - 8_0.txt
  - 8_1.txt
  - 8_2.txt
  cases/eval_1830.yaml:
  - 9_0.txt
  - 9_1.txt
  - 9_2.txt
  cases/eval_2073.yaml:
  - 10_0.txt
  - 10_1.txt
  - 10_2.txt
  cases/eval_2079.yaml:
  - 11_0.txt
  - 11_1.txt
  - 11_2.txt
  cases/eval_208.yaml:
  - 0_0.txt
  - 0_1.txt
  - 0_2.txt
  cases/eval_2748.yaml:
  - 12_0.txt
  - 12_1.txt
  - 12_2.txt
  cases/eval_310.yaml:
  - 1_0.txt
  - 1_1.txt
  - 1_2.txt
  cases/eval_3142.yaml:
  - 13_0.txt
  - 13_1.txt
  - 13_2.txt
  cases/eval_3401.yaml:
  - 14_0.txt
  - 14_1.txt
  - 14_2.txt
  cases/eval_3651.yaml:
  - 15_0.txt
  - 15_1.txt
  - 15_2.txt
  cases/eval_3790.yaml:
  - 16_0.txt
  - 16_1.txt
  - 16_2.txt
  cases/eval_4310.yaml:
  - 17_0.txt
  - 17_1.txt
  - 17_2.txt
  cases/eval_4548.yaml:
  - 18_0.txt
  - 18_1.txt
  - 18_2.txt
  cases/eval_4660.yaml:
  - 19_0.txt
  - 19_1.txt
  - 19_2.txt
  cases/eval_4741.yaml:
  - 20_0.txt
  - 20_1.txt
  - 20_2.txt
  cases/eval_5174.yaml:
  - 21_0.txt
  - 21_1.txt
  - 21_2.txt
  cases/eval_5460.yaml:
  - 22_0.txt
  - 22_1.txt
  - 22_2.txt
  cases/eval_5747.yaml:
  - 23_0.txt
  - 23_1.txt
  - 23_2.txt
  cases/eval_5749.yaml:
  - 24_0.txt
  - 24_1.txt
  - 24_2.txt
  cases/eval_5864.yaml:
  - 25_0.txt
  - 25_1.txt
  - 25_2.txt
  cases/eval_6407.yaml:
  - 26_0.txt
  - 26_1.txt
  - 26_2.txt
  cases/eval_6436.yaml:
  - 27_0.txt
  - 27_1.txt
  - 27_2.txt
  cases/eval_6495.yaml:
  - 28_0.txt
  - 28_1.txt
  - 28_2.txt
  cases/eval_652.yaml:
  - 2_0.txt
  - 2_1.txt
  - 2_2.txt
  cases/eval_703.yaml:
  - 3_0.txt
  - 3_1.txt
  - 3_2.txt
  cases/eval_7377.yaml:
  - 29_0.txt
  - 29_1.txt
  - 29_2.txt
  cases/eval_7500.yaml:
  - 30_0.txt
  - 30_1.txt
  - 30_2.txt
  cases/eval_7582.yaml:
  - 31_0.txt
  - 31_1.txt
  - 31_2.txt
  cases/eval_7617.yaml:
  - 32_0.txt
  - 32_1.txt
  - 32_2.txt
  cases/eval_7717.yaml:
  - 33_0.txt
  - 33_1.txt
  - 33_2.txt
  cases/eval_789.yaml:
  - 4_0.txt
  - 4_1.txt
  - 4_2.txt
  cases/eval_8143.yaml:
  - 34_0.txt
  - 34_1.txt
  - 34_2.txt
  cases/eval_8412.yaml:
  - 35_0.txt
  - 35_1.txt
  - 35_2.txt
  cases/eval_8897.yaml:
  - 36_0.txt
  - 36_1.txt
  - 36_2.txt
  cases/eval_8917.yaml:
  - 37_0.txt
  - 37_1.txt
  - 37_2.txt
  cases/eval_9098.yaml:
  - 38_0.txt
  - 38_1.txt
  - 38_2.txt
  cases/eval_938.yaml:
  - 5_0.txt
  - 5_1.txt
  - 5_2.txt
  cases/eval_9533.yaml:
  - 39_0.txt
  - 39_1.txt
  - 39_2.txt
max_tokens: null
model_name: gpt-3.5-turbo
sample_n: 3
system_prompt: You are a professional assistant for programmers. By default, questions
  are answers are in Markdown format.
temp: 0.2
top_p: 0.9
